// Central configuration for the self-contained figma-bridge-mcp server.
//
// The engine is vendored under ../engine and run as a child process with the
// SAME node binary that runs this server. There is no external CLI to
// locate — the FIGMA_CLI_BIN / FIGMA_CLI_ENTRY / FIGMA_CLI_CWD indirection of
// the old wrapper is gone.
import path from "node:path";
import { fileURLToPath } from "node:url";

// Repo root (one level up from src/).
export const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));

// Vendored engine entry point. Spawned with process.execPath.
export const ENGINE_ENTRY = fileURLToPath(
  new URL("../engine/src/index.js", import.meta.url),
);

// Working directory for the engine child. The repo root is stable regardless of
// where the MCP client launched the server from.
export const ENGINE_CWD = REPO_ROOT;

// Base directory for all local state (token, pid, key, audit log). Kept
// separate from any upstream figma-ds-cli install so the two never share a
// daemon, token, or port-owner. Single source of truth lives in the engine
// lib (which also migrates ~/.figma-safe-mcp from pre-rename installs once).
import { STATE_DIR } from "../engine/src/lib/state-dir.js";
export { STATE_DIR };

// Audit log path.
export const AUDIT_LOG_PATH =
  process.env.AUDIT_LOG_PATH || path.join(STATE_DIR, "audit.log");

// Plugin access-key file. The daemon reads this (via PLUGIN_KEY_FILE env) to
// authenticate the plugin WebSocket handshake. 0600, generated by pairing.js.
export const PLUGIN_KEY_FILE =
  process.env.PLUGIN_KEY_FILE || path.join(STATE_DIR, "plugin-key");

// Optional Figma REST token (PAT). Written 0600 by the DAEMON when the user
// pastes it into the plugin UI (never through chat or MCP client config);
// read here for the opt-in REST tools. FIGMA_REST_TOKEN env overrides the
// file for headless/CI use — see figma-rest.js.
export const REST_TOKEN_FILE =
  process.env.REST_TOKEN_FILE || path.join(STATE_DIR, "rest-token");

// Timeout for a single engine invocation (ms).
export const EXEC_TIMEOUT_MS = Number(process.env.EXEC_TIMEOUT_MS) || 60000;

// Durations for the Capability Catalog's execution classes. The Catalog owns
// which Figma Command is long/background; configuration only maps that policy
// to deployment-specific milliseconds. ASSET_EXPORT_TIMEOUT_MS remains a
// supported compatibility name for existing installations.
export const LONG_EXEC_TIMEOUT_MS =
  Number(process.env.LONG_EXEC_TIMEOUT_MS) || Math.max(EXEC_TIMEOUT_MS, 120_000);
export const BACKGROUND_EXEC_TIMEOUT_MS =
  Number(process.env.BACKGROUND_EXEC_TIMEOUT_MS) ||
  Number(process.env.ASSET_EXPORT_TIMEOUT_MS) ||
  10 * 60 * 1000;

// Hard cap for `connect --safe --no-wait` (ms). The command only starts the
// detached daemon and refreshes the plugin files; it never waits for Figma.
// Its own readiness loop is capped at 2s, so 5s leaves startup headroom while
// keeping a broken setup responsive.
export const CONNECT_TIMEOUT_MS =
  Number(process.env.CONNECT_TIMEOUT_MS) || 5000;

// Daemon endpoint (Safe Mode). The port is resolved fresh per call by the
// engine's shared resolver (env DAEMON_PORT > port file published by the
// daemon > 3456) — the daemon may have fallen back within 3456-3460 when the
// default port was held by a foreign process.
export const DAEMON_HOST = process.env.DAEMON_HOST || "127.0.0.1";
export { getDaemonPort } from "../engine/src/lib/daemon-port.js";
export const DAEMON_TOKEN_FILE =
  process.env.DAEMON_TOKEN_FILE || path.join(STATE_DIR, ".daemon-token");

// Optional write-confirm / dry-run mode. When "1", write commands require an
// explicit confirm flag before they are executed.
export const WRITE_CONFIRM = process.env.FIGMA_WRITE_CONFIRM === "1";

/**
 * Build the concrete command + argv for spawning the vendored engine.
 * Always uses the current node binary + the vendored entry point.
 *
 * @param {string[]} userArgs - the engine subcommand + flags (already an array).
 * @param {{fileKey?: string|null}} [opts] - `fileKey` targets one of several
 *   connected Figma windows. Prepended as the GLOBAL `--figma-file` option,
 *   since commander requires global options before the command name — and added
 *   here, after the caller's allowlist check has already seen the real command,
 *   so a leading flag can never smuggle past that check. The name avoids
 *   `--file`, which eval and spec already use for a local path.
 * @returns {{cmd: string, argv: string[]}}
 */
export function buildArgv(userArgs, opts = {}) {
  if (!Array.isArray(userArgs)) {
    throw new Error("buildArgv: userArgs must be an array");
  }
  const key = opts.fileKey ? String(opts.fileKey).trim() : "";
  const global = key ? ["--figma-file", key] : [];
  return { cmd: process.execPath, argv: [ENGINE_ENTRY, ...global, ...userArgs] };
}
