// Central configuration for the self-contained figma-safe-mcp server.
//
// The engine is vendored under ../engine and run as a child process with the
// SAME node binary that runs this server. There is no external figma-cli to
// locate — the FIGMA_CLI_BIN / FIGMA_CLI_ENTRY / FIGMA_CLI_CWD indirection of
// the old wrapper is gone.
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Repo root (one level up from src/).
export const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));

// Vendored engine entry point. Spawned with process.execPath.
export const ENGINE_ENTRY = fileURLToPath(
  new URL("../engine/src/index.js", import.meta.url),
);

// Working directory for the engine child. The repo root is stable regardless of
// where the MCP client launched the server from.
export const ENGINE_CWD = REPO_ROOT;

// Base directory for all local state (token, pid, key, audit log). Kept
// separate from any upstream figma-ds-cli install so the two never share a
// daemon, token, or port-owner.
export const STATE_DIR = path.join(os.homedir(), ".figma-safe-mcp");

// Audit log path.
export const AUDIT_LOG_PATH =
  process.env.AUDIT_LOG_PATH || path.join(STATE_DIR, "audit.log");

// Plugin access-key file. The daemon reads this (via PLUGIN_KEY_FILE env) to
// authenticate the plugin WebSocket handshake. 0600, generated by pairing.js.
export const PLUGIN_KEY_FILE =
  process.env.PLUGIN_KEY_FILE || path.join(STATE_DIR, "plugin-key");

// Timeout for a single engine invocation (ms).
export const EXEC_TIMEOUT_MS = Number(process.env.EXEC_TIMEOUT_MS) || 60000;

// Timeout for `connect --safe` (ms). The engine prints its daemon-started +
// plugin-import instructions within ~1-2s, then blocks up to 90s waiting for
// the plugin to connect. Because the daemon is spawned detached (unref'd), we
// kill the connect process after capturing the instructions without stopping
// the daemon. Keep this well under the engine's 90s wait.
export const CONNECT_TIMEOUT_MS =
  Number(process.env.CONNECT_TIMEOUT_MS) || 12000;

// Daemon endpoint (Safe Mode). The port is resolved fresh per call by the
// engine's shared resolver (env DAEMON_PORT > port file published by the
// daemon > 3456) — the daemon may have fallen back within 3456-3460 when the
// default port was held by a foreign process.
export const DAEMON_HOST = process.env.DAEMON_HOST || "127.0.0.1";
export { getDaemonPort } from "../engine/src/lib/daemon-port.js";
export const DAEMON_TOKEN_FILE =
  process.env.DAEMON_TOKEN_FILE || path.join(STATE_DIR, ".daemon-token");

// Optional write-confirm / dry-run mode. When "1", write commands require an
// explicit confirm flag before they are executed.
export const WRITE_CONFIRM = process.env.FIGMA_WRITE_CONFIRM === "1";

/**
 * Build the concrete command + argv for spawning the vendored engine.
 * Always uses the current node binary + the vendored entry point.
 *
 * @param {string[]} userArgs - the engine subcommand + flags (already an array).
 * @returns {{cmd: string, argv: string[]}}
 */
export function buildArgv(userArgs) {
  if (!Array.isArray(userArgs)) {
    throw new Error("buildArgv: userArgs must be an array");
  }
  return { cmd: process.execPath, argv: [ENGINE_ENTRY, ...userArgs] };
}
