#!/usr/bin/env node

/**
 * Figma Bridge MCP Daemon (Safe-Mode / plugin bridge only)
 *
 * The upstream figma-ds-cli daemon supported two transports: Yolo Mode (Chrome
 * DevTools Protocol, requires patching Figma) and Safe Mode (the Figma plugin
 * WebSocket). This build keeps ONLY the plugin bridge — there is no CDP path.
 *
 * Security features:
 * - Per-request HMAC signing on all HTTP routes (X-Daemon-Ts/-Nonce/-Auth,
 *   keyed with the session token — the token itself never crosses the wire,
 *   so a squatter on a range port cannot harvest and replay it)
 * - Plugin access-key authentication on the WebSocket /plugin upgrade:
 *     · verifyClient: Host + Origin allowlist (blocks DNS rebinding / browsers)
 *     · mutual challenge-response handshake (lib/plugin-handshake.js): the key
 *       is an HMAC secret, never a wire value, both sides prove possession, and
 *       the bound port is inside the transcript so a relaying squatter fails.
 *       Closes the upstream gap where ANY local process could connect to
 *       /plugin and eval code in Figma — and the inverse gap, where any local
 *       process could impersonate the daemon and drive an honest plugin.
 * - No CORS headers (blocks cross-origin browser requests)
 * - Idle timeout auto-shutdown
 */

import { createServer } from 'http';
import { randomUUID } from 'crypto';
import { WebSocketServer, WebSocket } from 'ws';
import { readFileSync, writeFileSync, unlinkSync, mkdirSync, chmodSync } from 'fs';
import { join, dirname } from 'path';
import { parsePortRange, writePortFile, clearPortFile } from './lib/daemon-port.js';
import { verifyRequest, AUTH_WINDOW_MS } from './lib/daemon-auth.js';
import {
  HANDSHAKE_PROTO,
  makeNonce,
  isNonce,
  pluginTranscript,
  daemonTranscript,
  sign as signHandshake,
  verify as verifyHandshake,
} from './lib/plugin-handshake.js';
import { STATE_DIR } from './lib/state-dir.js';
import { getPortPid } from './platform.js';
import { validateExecPayload, validatePluginMessage } from './lib/protocol-contract.js';
import { PLUGIN_BUILD_VERSION, pluginUpdateAvailable } from './lib/plugin-version.js';

// Explicit DAEMON_PORT means "exactly this port, no fallback" (the plugin can
// only reach the manifest range — off-range values are documented unsupported).
// Without it, the daemon walks the range and binds the first free port, which
// the plugin's parallel port scan finds on its own.
// Invalid values (non-numeric, > 65535) are warned about and IGNORED — the
// same silent-discard the resolver in daemon-port.js applies, but named, so
// the daemon no longer dies later with an opaque ERR_SOCKET_BAD_PORT.
const EXPLICIT_RAW = process.env.DAEMON_PORT;
const EXPLICIT_PORT = parseInt(EXPLICIT_RAW, 10);
const EXPLICIT_VALID = Number.isInteger(EXPLICIT_PORT) && EXPLICIT_PORT > 0 && EXPLICIT_PORT < 65536;
if (EXPLICIT_RAW && !EXPLICIT_VALID) {
  console.error(`[daemon] Ignoring invalid DAEMON_PORT="${EXPLICIT_RAW}" (expected 1-65535) — using the default range.`);
}
const PORT_CANDIDATES = EXPLICIT_VALID ? [EXPLICIT_PORT] : parsePortRange();
let boundPort = null; // set once the HTTP server wins a bind
// Safe-Mode build: the daemon is always the plugin bridge. Kept as a constant
// (not env-driven) so no configuration can re-enable a CDP path.
const MODE = 'plugin';
const IDLE_TIMEOUT_MS = parseInt(process.env.DAEMON_IDLE_TIMEOUT) || 60 * 60 * 1000; // 60 minutes

// ============ SECURITY ============

// Session token (HTTP routes) — generated by the CLI on daemon start.
// Env-overridable so tests can point at scratch files; defaults match cli-core.
const TOKEN_FILE = process.env.DAEMON_TOKEN_FILE || join(STATE_DIR, '.daemon-token');
// Singleton PID file, claimed only by the daemon that wins the port bind.
const PID_FILE = process.env.DAEMON_PID_FILE || join(STATE_DIR, 'daemon.pid');

// Session token is read PER REQUEST, not once at startup: startDaemon() rotates
// the token file before every spawn, and a lost spawn race (two CLIs starting
// daemons concurrently; the loser exits but has already rotated the file) would
// otherwise leave the surviving daemon holding a stale token — rejecting every
// request with 403 until a manual restart. The file is ~64 bytes and local;
// a read per request is negligible.
function readSessionToken() {
  try {
    return readFileSync(TOKEN_FILE, 'utf8').trim() || null;
  } catch {
    return null;
  }
}

if (readSessionToken()) {
  console.log('[daemon] Session token loaded');
} else {
  console.error('[daemon] WARNING: No session token found. Daemon will reject all HTTP requests.');
}

// Plugin access key (WebSocket /plugin auth). Path passed by the MCP layer via
// PLUGIN_KEY_FILE. Absent/empty key ⇒ ALL plugin connections are rejected.
const PLUGIN_KEY_FILE = process.env.PLUGIN_KEY_FILE || '';
let PLUGIN_KEY = null;

if (PLUGIN_KEY_FILE) {
  try {
    const k = readFileSync(PLUGIN_KEY_FILE, 'utf8').trim();
    PLUGIN_KEY = k || null;
  } catch {
    PLUGIN_KEY = null;
  }
}
if (PLUGIN_KEY) {
  console.log('[daemon] Plugin access key loaded');
} else {
  console.error('[daemon] WARNING: No plugin access key. Plugin connections will be rejected. Run figma_connect.');
}

// Optional Figma REST token (PAT). The user pastes it into the PLUGIN UI, it
// travels over the authenticated WebSocket, and the daemon persists it here
// (0600). The MCP layer reads this file for its REST calls — the token never
// appears in chat, MCP client config, or the audit log. Path is passed by the
// MCP layer via REST_TOKEN_FILE (same pattern as PLUGIN_KEY_FILE).
const REST_TOKEN_FILE = process.env.REST_TOKEN_FILE || join(STATE_DIR, 'rest-token');

function restTokenConfigured() {
  try {
    return readFileSync(REST_TOKEN_FILE, 'utf8').trim().length > 0;
  } catch {
    return false;
  }
}

// Store (non-empty value) or clear (empty value) the REST token. 0600 +
// chmod-tighten in case the file pre-existed with looser perms.
function saveRestToken(value) {
  const v = String(value || '').trim();
  if (!v) {
    try { unlinkSync(REST_TOKEN_FILE); } catch {}
    return false;
  }
  mkdirSync(dirname(REST_TOKEN_FILE), { recursive: true, mode: 0o700 });
  writeFileSync(REST_TOKEN_FILE, v, { mode: 0o600 });
  try { chmodSync(REST_TOKEN_FILE, 0o600); } catch {}
  return true;
}

// Handshake nonces the daemon has already honoured. A plugin proof is bound to
// a nonce pair the daemon itself generated, so replay is already impossible
// across sockets — this guards the degenerate case of the SAME challenge being
// answered twice on one socket, and keeps the guarantee explicit rather than
// implied. Pruned on the same schedule as the HTTP nonce cache.
const seenHandshakeNonces = new Map(); // pluginNonce → first-seen ms
function handshakeNonceReplayed(nonce, now = Date.now()) {
  for (const [n, t] of seenHandshakeNonces) {
    if (now - t > AUTH_WINDOW_MS * 2) seenHandshakeNonces.delete(n);
  }
  if (seenHandshakeNonces.has(nonce)) return true;
  seenHandshakeNonces.set(nonce, now);
  return false;
}

// Replay guard for the signed-request auth: every accepted nonce is remembered
// for the freshness window; a verbatim replay of harvested headers is rejected
// even inside the window. Pruned inline — the map stays tiny (one entry per
// request per ~60s).
const seenNonces = new Map(); // nonce → first-seen ms
function nonceReplayed(nonce, now = Date.now()) {
  for (const [n, t] of seenNonces) {
    if (now - t > AUTH_WINDOW_MS * 2) seenNonces.delete(n);
  }
  if (seenNonces.has(nonce)) return true;
  seenNonces.set(nonce, now);
  return false;
}

/**
 * Validate HTTP request authentication and origin.
 * Returns null if valid, or an error string if rejected.
 * `body` must be the exact raw request body ('' for body-less requests) —
 * the signature binds it, so it has to be read before validation on POSTs.
 */
function validateRequest(req, body = '') {
  // Layer 1: Host header validation (blocks DNS rebinding)
  const host = req.headers.host || '';
  if (!host.match(/^(?:localhost|127\.0\.0\.1|\[::1\])(?::\d+)?$/)) {
    return 'Invalid host header';
  }

  // Layer 2: signed request (blocks unauthorized local processes; the session
  // token never crosses the wire). Token read fresh per request so a rotation
  // under a live daemon heals instead of wedging every consumer on 403.
  const sessionToken = readSessionToken();
  if (!sessionToken) {
    return 'No session token configured';
  }
  const path = (req.url || '').split('?')[0];
  if (!verifyRequest(sessionToken, req.headers, req.method || 'GET', path, body)) {
    return 'Invalid or missing request signature';
  }
  if (nonceReplayed(req.headers['x-daemon-nonce'])) {
    return 'Replayed request nonce';
  }

  return null; // Valid
}

// ============ IDLE TIMEOUT ============

let lastActivityTime = Date.now();
let idleTimer = null;

function resetIdleTimer() {
  lastActivityTime = Date.now();
  if (idleTimer) clearTimeout(idleTimer);
  idleTimer = setTimeout(() => {
    const idleSecs = Math.round((Date.now() - lastActivityTime) / 1000);
    console.log(`[daemon] Idle for ${idleSecs}s — auto-shutting down`);
    shutdown();
  }, IDLE_TIMEOUT_MS);
}

resetIdleTimer();

// ============ PLUGIN MODE (SAFE) ============

// Every authenticated plugin socket, one entry per open Figma window.
//
// Multiple windows are allowed, but they are NOT a fan-out: each one is a
// separate document the user themselves opened and started the plugin in, so
// the consent is physical rather than configured, and a command still has to
// name which file it means. There is deliberately no "all files" switch.
//
// File identity arrives with the first selection push (the plugin sends one
// immediately on connect) — the handshake itself carries no file information,
// and adding it there would mean signing data the transcript does not cover.
const conns = new Map(); // ws → { connectionId, fileKey, fileName, editorType, capabilities, pluginVersion, pluginUpdateAvailable, selection, connectedAt, lastResponseAt }
let pluginPendingRequests = new Map(); // id → { resolve, reject, timeout, ws }
let pluginMsgId = 0;

function openConns() {
  return [...conns.entries()].filter(([ws]) => ws.readyState === WebSocket.OPEN);
}

function isPluginConnected() {
  return openConns().length > 0;
}

/** Public shape of the connection list — no socket, no internals. */
function connectionList() {
  return openConns().map(([, c]) => ({
    connectionId: c.connectionId,
    fileKey: c.fileKey ?? null,
    fileName: c.fileName ?? null,
    editorType: c.editorType ?? null,
    capabilities: c.capabilities || [],
    pluginVersion: c.pluginVersion ?? null,
    pluginUpdateAvailable: c.pluginUpdateAvailable === true,
    connectedAt: c.connectedAt,
    lastResponseAt: c.lastResponseAt ?? null,
  }));
}

/**
 * Pick the socket a command should go to.
 *
 * One connection: it wins, named or not — the single-file case must not get
 * harder just because the daemon can now hold several.
 * Several: `fileKey` is required, and an unmatched or missing one is an error
 * that lists what IS connected. Guessing here would run an agent's write
 * against whichever window happened to connect last.
 */
function resolveTarget(fileKey) {
  const open = openConns();
  if (!open.length) {
    throw new Error('Plugin not connected. Launch the Figma Bridge plugin in Figma and paste your access key.');
  }
  const wanted = fileKey ? String(fileKey) : null;

  if (wanted) {
    const hit = open.find(([, c]) => c.fileKey === wanted);
    if (hit) return hit[0];
    const known = connectionList()
      .map((c) => `  ${c.fileKey || '(unidentified)'}  ${c.fileName || ''}`.trimEnd())
      .join('\n');
    throw new Error(
      `No connected Figma window has file key "${wanted}". Connected:\n${known}`,
    );
  }

  if (open.length === 1) return open[0][0];

  const known = connectionList()
    .map((c) => `  ${c.fileKey || '(unidentified)'}  ${c.fileName || ''}`.trimEnd())
    .join('\n');
  throw new Error(
    `${open.length} Figma windows are connected — name one with fileKey. Connected:\n${known}\n`
    + 'There is no "all files" option: each file is targeted explicitly.',
  );
}

async function requestViaPlugin(action, data, fileKey = null) {
  const ws = resolveTarget(fileKey);
  const conn = conns.get(ws);
  if (action === 'render-plan' && !conn?.capabilities?.includes('render-plan-v1')) {
    throw new Error('Plugin capability missing: render-plan-v1. Reload the installed Figma Bridge plugin to enable structured rendering.');
  }
  if (action === 'render-plan-batch' && !conn?.capabilities?.includes('render-plan-batch-v1')) {
    throw new Error('Plugin capability missing: render-plan-batch-v1. Reload the installed Figma Bridge plugin to enable structured batch rendering.');
  }

  return new Promise((resolve, reject) => {
    const id = ++pluginMsgId;
    const timeout = setTimeout(() => {
      pluginPendingRequests.delete(id);
      reject(new Error('Plugin execution timeout (25s)'));
    }, 25000);

    pluginPendingRequests.set(id, { resolve, reject, timeout, ws });

    try {
      ws.send(JSON.stringify({ action, id, ...data }));
    } catch (sendError) {
      clearTimeout(timeout);
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin send error: ${sendError.message}`));
    }
  });
}

// ============ UNIFIED EVAL ============

async function executeEval(code, fileKey = null) {
  // Plugin handles its own top-level-return wrapping — send code as-is.
  return requestViaPlugin('eval', { code }, fileKey);
}

async function executeRenderPlan(plan, fileKey = null) {
  return requestViaPlugin('render-plan', { plan }, fileKey);
}

async function executeRenderPlanBatch(plans, options, fileKey = null) {
  return requestViaPlugin('render-plan-batch', { plans, options }, fileKey);
}

function resultMetadata(ws, raw) {
  const conn = conns.get(ws);
  const before = Number.isSafeInteger(raw?.documentRevisionBefore) && raw.documentRevisionBefore >= 0
    ? raw.documentRevisionBefore : null;
  const after = Number.isSafeInteger(raw?.documentRevisionAfter) && raw.documentRevisionAfter >= 0
    ? raw.documentRevisionAfter : null;
  return {
    connectionId: conn?.connectionId || null,
    fileKey: conn?.fileKey || null,
    documentRevisionBefore: before,
    documentRevisionAfter: after,
  };
}

function getMode() {
  return isPluginConnected() ? 'safe' : 'disconnected';
}

// ============ HTTP SERVER ============

// In-flight /exec responses. shutdown() drains these before closing the
// plugin socket — closing it first reset every running eval mid-flight.
let inFlightExecs = 0;

async function handleRequest(req, res) {
  resetIdleTimer();

  // SECURITY: No CORS headers. Block preflight outright.
  if (req.method === 'OPTIONS') {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'CORS preflight rejected' }));
    return;
  }

  // Execute command. The request signature binds the body, so the body must be
  // collected BEFORE authentication — this route validates itself below.
  if (req.url === '/exec' && req.method === 'POST') {
    handleExec(req, res);
    return;
  }

  // SECURITY: Validate authentication on all remaining (body-less) routes.
  const authError = validateRequest(req, '');
  if (authError) {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized: ' + authError }));
    return;
  }

  // Routes below may carry a ?fileKey= query, so match on the path alone —
  // the same path validateRequest() signs over (queries are outside the
  // signature). That is deliberate and not an escalation: the query only
  // selects WHICH connected window to read, and every connected window is
  // equally authorised. Anything that grants access stays in the signed part.
  const path = (req.url || '').split('?')[0];

  // Health check
  if (path === '/health') {
    const pluginConnected = isPluginConnected();
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: pluginConnected ? 'ok' : 'disconnected',
      mode: getMode(),
      plugin: pluginConnected,
      pluginAuthenticated: pluginConnected, // only authenticated sockets are stored
      cdp: false,                            // no CDP path in the Safe-Mode build
      keyConfigured: !!PLUGIN_KEY,
      restTokenConfigured: restTokenConfigured(),
      // One entry per open Figma window. Callers that see more than one must
      // name a fileKey; there is no implicit "all of them".
      connections: connectionList(),
      idleTimeoutMs: IDLE_TIMEOUT_MS
    }));
    return;
  }

  // Last selection the plugin UI pushed (button or selectionchange event).
  // Read by the MCP tool figma_selection. With several windows connected the
  // caller may name one; without a name the single connection wins and
  // anything else is ambiguous rather than arbitrary.
  if (path === '/selection') {
    const wanted = new URL(req.url, 'http://localhost').searchParams.get('fileKey');
    const open = openConns();
    let selection = null;
    let ambiguous = false;
    if (wanted) {
      const hit = open.find(([, c]) => c.fileKey === wanted);
      selection = hit ? hit[1].selection ?? null : null;
    } else if (open.length === 1) {
      selection = open[0][1].selection ?? null;
    } else if (open.length > 1) {
      ambiguous = true;
    }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      selection,
      pluginConnected: isPluginConnected(),
      connections: connectionList(),
      ...(ambiguous ? { ambiguous: true } : {}),
    }));
    return;
  }

  // Force the plugin to reconnect: close its socket — the plugin UI re-scans
  // the whole port range automatically. Used by `daemon reconnect` (this route
  // did not exist before; the command always failed on the 404 fallthrough).
  if (path === '/reconnect') {
    const wanted = new URL(req.url, 'http://localhost').searchParams.get('fileKey');
    const targets = openConns().filter(([, c]) => !wanted || c.fileKey === wanted);
    for (const [ws] of targets) {
      try { ws.close(); } catch {}
    }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, hadPlugin: targets.length > 0, closed: targets.length }));
    return;
  }

  res.writeHead(404);
  res.end('Not found');
}

function handleExec(req, res) {
  let body = '';
  req.on('data', chunk => body += chunk);
  req.on('end', async () => {
    // SECURITY: the signature covers the exact body — validate only now.
    const authError = validateRequest(req, body);
    if (authError) {
      res.writeHead(403, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Unauthorized: ' + authError }));
      return;
    }

    let payload;
    try {
      payload = JSON.parse(body);
    } catch (e) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Invalid JSON body: ' + e.message }));
      return;
    }
    const payloadError = validateExecPayload(payload);
    if (payloadError) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Invalid execution request: ' + payloadError }));
      return;
    }

    // NO retries for ANY action: every action ultimately evals arbitrary,
    // usually MUTATING code in the plugin. On a timeout/disconnect the code
    // may still complete in Figma — re-sending it silently DUPLICATES the
    // mutation (frames, variables, node edits). The earlier retry loop
    // exempted only render/render-batch and re-ran evals; that was wrong.
    inFlightExecs++;
    try {
      const { action, code, plan, plans, options, timeoutMs, fileKey } = payload;
      let result;
      let metadata = null;

      const execWithTimeout = async (fn, ms = 30000) => {
        return Promise.race([
          fn(),
          new Promise((_, reject) =>
            setTimeout(() => reject(new Error(`Execution timeout (${ms / 1000}s)`)), ms)
          )
        ]);
      };

      switch (action) {
        // `eval` remains the compatibility action. `render-plan` carries the
        // validated Semantic Render Plan to the plugin's static native
        // executor; unlike the removed daemon-side JSX render actions it does
        // not keep a second parser/compiler or lose CLI-side semantic state.
        // Long renders pass their budget via timeoutMs (clamped: a client
        // must not be able to disable the timeout entirely).
        case 'eval': {
          const ms = Math.min(Math.max(Number(timeoutMs) || 30000, 1000), 120000);
          const execution = await execWithTimeout(() => executeEval(code, fileKey || null), ms);
          result = execution.result;
          metadata = execution.metadata;
          break;
        }
        case 'render-plan': {
          const ms = Math.min(Math.max(Number(timeoutMs) || 30000, 1000), 120000);
          const execution = await execWithTimeout(() => executeRenderPlan(plan, fileKey || null), ms);
          result = execution.result;
          metadata = execution.metadata;
          break;
        }
        case 'render-plan-batch': {
          const ms = Math.min(Math.max(Number(timeoutMs) || 30000, 1000), 120000);
          const execution = await execWithTimeout(() => executeRenderPlanBatch(plans, options || {}, fileKey || null), ms);
          result = execution.result;
          metadata = execution.metadata;
          break;
        }
        default:
          throw new Error(`Unknown action: ${action}`);
      }

      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ result, metadata, mode: getMode() }));
    } catch (error) {
      console.log(`[daemon] /exec failed: ${error.message}`);
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: error.message || 'Execution failed' }));
    } finally {
      inFlightExecs--;
    }
  });
}

// ============ START SERVERS ============

const httpServer = createServer(handleRequest);
const ipv6HttpServer = createServer(handleRequest);

// WebSocket server for plugin connections.
// verifyClient is the first gate: only localhost Host headers and the sandboxed
// Figma plugin origin (null/absent) or figma.com are allowed through. Everything
// else — including any browser page on another origin — is rejected with 401.
function verifyPluginClient(info) {
    const req = info.req;
    const host = req.headers.host || '';
    if (!/^(?:localhost|127\.0\.0\.1|\[::1\])(?::\d+)?$/.test(host)) return false;
    const origin = info.origin;
    if (origin && origin !== 'null' && !/^https:\/\/(www\.)?figma\.com$/.test(origin)) {
      return false;
    }
    return true;
}

const wss = new WebSocketServer({ server: httpServer, path: '/plugin', verifyClient: verifyPluginClient });
const ipv6Wss = new WebSocketServer({ server: ipv6HttpServer, path: '/plugin', verifyClient: verifyPluginClient });

// ws re-emits the underlying server's errors (including the EADDRINUSE of a
// failed bind attempt) on the WebSocketServer. Without a listener that becomes
// an uncaught 'error' event and kills the process before the fallback loop in
// start() can try the next port. The HTTP-server side owns PRE-bind error
// handling — but post-bind ws-server errors must not vanish silently, so they
// are logged once the daemon holds a port.
for (const socketServer of [wss, ipv6Wss]) {
  socketServer.on('error', (err) => {
    if (boundPort !== null) console.error('[daemon] WebSocket server error:', err.message);
  });
}

const AUTH_TIMEOUT_MS = 5000;

function handlePluginSocket(ws) {
  // Each socket starts unauthenticated. The daemon speaks first with a random
  // challenge; the FIRST message back must be a {type:'hello'} carrying a proof
  // over (our nonce, their nonce, our bound port, their version). Until that
  // verifies, the socket is not registered in `conns` and cannot drive any
  // eval. See lib/plugin-handshake.js for why the port is in the transcript.
  let authenticated = false;

  // If no key is configured on the daemon, we can never authenticate — reject.
  if (!PLUGIN_KEY) {
    try { ws.send(JSON.stringify({ type: 'auth-error', reason: 'no-key-configured' })); } catch {}
    ws.close(4401, 'No access key configured on daemon');
    return;
  }

  const daemonNonce = makeNonce();
  try {
    ws.send(JSON.stringify({
      type: 'challenge',
      proto: HANDSHAKE_PROTO,
      nonce: daemonNonce,
      port: boundPort,
    }));
  } catch {}

  const authTimer = setTimeout(() => {
    if (!authenticated) {
      try { ws.send(JSON.stringify({ type: 'auth-error', reason: 'timeout' })); } catch {}
      ws.close(4401, 'Authentication timeout');
    }
  }, AUTH_TIMEOUT_MS);

  ws.on('message', (data) => {
    resetIdleTimer();
    let msg;
    try {
      msg = JSON.parse(data.toString());
    } catch (e) {
      console.error('[daemon] Plugin message parse error:', e.message);
      return;
    }

    // Classify a stale pre-auth hello before the strict proto-2 shape check.
    // Proto 1 sent the raw key and therefore lacks the nonce/proof fields that
    // validatePluginMessage intentionally requires. If validation ran first,
    // the actionable re-import signal would be collapsed into "protocol".
    if (!authenticated
      && msg !== null
      && typeof msg === 'object'
      && !Array.isArray(msg)
      && msg.type === 'hello'
      && msg.proto !== HANDSHAKE_PROTO) {
      try { ws.send(JSON.stringify({ type: 'auth-error', reason: 'proto-mismatch' })); } catch {}
      ws.close(4401, 'Plugin handshake version mismatch');
      return;
    }
    const messageError = validatePluginMessage(msg, { authenticated });
    if (messageError) {
      if (!authenticated) {
        try { ws.send(JSON.stringify({ type: 'auth-error', reason: 'protocol' })); } catch {}
        ws.close(4401, messageError);
      } else {
        console.error('[daemon] Plugin protocol error:', messageError);
      }
      return;
    }

    // --- Authentication gate ---
    if (!authenticated) {
      const reject = (reason, closeText) => {
        try { ws.send(JSON.stringify({ type: 'auth-error', reason })); } catch {}
        ws.close(4401, closeText);
      };

      if (msg.type !== 'hello') {
        return reject('invalid-key', 'Expected hello');
      }
      // A proto-1 plugin (raw `key` frame, no proof) is a stale install, not a
      // weaker peer to accommodate: figma_connect ships both sides together.
      // Name it so the user re-imports instead of debugging a generic rejection.
      if (msg.proto !== HANDSHAKE_PROTO) {
        return reject('proto-mismatch', 'Plugin handshake version mismatch');
      }
      if (!isNonce(msg.nonce) || handshakeNonceReplayed(msg.nonce)) {
        return reject('invalid-key', 'Bad or reused handshake nonce');
      }
      const version = String(msg.version || 'unknown');
      const updateAvailable = pluginUpdateAvailable(version);
      const expected = pluginTranscript({
        daemonNonce,
        pluginNonce: msg.nonce,
        port: boundPort,
        version,
      });
      if (!verifyHandshake(PLUGIN_KEY, expected, msg.proof)) {
        return reject('invalid-key', 'Invalid access key');
      }

      // Authenticated. Registered without a file identity: that arrives with
      // the first selection push, which the plugin sends as soon as it is
      // connected.
      authenticated = true;
      clearTimeout(authTimer);
      conns.set(ws, {
        connectionId: randomUUID(),
        fileKey: null, fileName: null, editorType: null,
        capabilities: Array.isArray(msg.capabilities)
          ? msg.capabilities.filter((item) => ['render-plan-v1', 'render-plan-batch-v1'].includes(item)) : [],
        pluginVersion: version,
        pluginUpdateAvailable: updateAvailable,
        selection: null, connectedAt: new Date().toISOString(), lastResponseAt: null,
      });
      console.log(`[daemon] Plugin authenticated (version: ${version}) — ${openConns().length} window(s) connected`);
      // Prove ourselves back before the plugin will accept a single eval.
      try {
        ws.send(JSON.stringify({
          type: 'hello-ack',
          proto: HANDSHAKE_PROTO,
          proof: signHandshake(PLUGIN_KEY, daemonTranscript({
            daemonNonce,
            pluginNonce: msg.nonce,
            port: boundPort,
          })),
          restTokenConfigured: restTokenConfigured(),
          pluginVersion: version,
          bundledPluginVersion: PLUGIN_BUILD_VERSION,
          pluginUpdateAvailable: updateAvailable,
        }));
      } catch {}
      return;
    }

    // --- Authenticated message handling ---
    if (msg.type === 'result') {
      const pending = pluginPendingRequests.get(msg.id);
      if (pending && pending.ws === ws) {
        const conn = conns.get(ws);
        if (conn) conn.lastResponseAt = new Date().toISOString();
        clearTimeout(pending.timeout);
        pluginPendingRequests.delete(msg.id);
        if (msg.error) pending.reject(new Error(msg.error));
        else pending.resolve({ result: msg.result, metadata: resultMetadata(ws, msg.metadata) });
      }
    }

    if (msg.type === 'batch-result') {
      const pending = pluginPendingRequests.get(msg.id);
      if (pending) {
        const conn = conns.get(ws);
        if (conn) conn.lastResponseAt = new Date().toISOString();
        clearTimeout(pending.timeout);
        pluginPendingRequests.delete(msg.id);
        pending.resolve(msg.results);
      }
    }

    if (msg.type === 'ping') {
      try { ws.send(JSON.stringify({ type: 'pong' })); } catch {}
    }

    // REST-token save/clear from the plugin UI. Only reachable on the
    // authenticated socket — an unauthenticated local process cannot plant or
    // wipe the token. Empty value clears. The value is never echoed back and
    // never logged; the ack carries only the configured flag.
    if (msg.type === 'rest-token') {
      let configured = false;
      let error = null;
      try {
        configured = saveRestToken(msg.value);
      } catch (e) {
        error = e.message || String(e);
        configured = restTokenConfigured();
      }
      try {
        ws.send(JSON.stringify({ type: 'rest-token-ack', configured, ...(error ? { error } : {}) }));
      } catch {}
    }

    // Selection push from the plugin (automatic, debounced selectionchange
    // events). Cached here; served via GET /selection so the MCP tool
    // figma_selection can read it. Only the authenticated socket reaches
    // this handler.
    if (msg.type === 'selection' && msg.selection && typeof msg.selection === 'object') {
      const selection = {
        page: String(msg.selection.page || ''),
        total: Number(msg.selection.total) || 0,
        // File identity (needs enablePrivatePluginApi in the plugin manifest;
        // fileKey is undefined for never-saved drafts). Whitelisted like the
        // component keys below — unknown fields are silently dropped.
        ...(typeof msg.selection.fileKey === 'string' && msg.selection.fileKey
          ? { fileKey: msg.selection.fileKey.slice(0, 64) } : {}),
        ...(typeof msg.selection.fileName === 'string' && msg.selection.fileName
          ? { fileName: msg.selection.fileName.slice(0, 128) } : {}),
        // Which editor the plugin is running in ("figma" | "figjam" | "slides").
        ...(typeof msg.selection.editorType === 'string' && msg.selection.editorType
          ? { editorType: msg.selection.editorType.slice(0, 16) } : {}),
        nodes: Array.isArray(msg.selection.nodes)
          ? msg.selection.nodes.slice(0, 50).map((n) => ({
              id: String(n.id || ''),
              name: String(n.name || ''),
              type: String(n.type || ''),
              ...(Number.isFinite(n.width) ? { width: n.width } : {}),
              ...(Number.isFinite(n.height) ? { height: n.height } : {}),
              // Component identity (stable publish keys) — whitelist them
              // explicitly or they are silently dropped here.
              ...(typeof n.componentKey === 'string' && n.componentKey ? { componentKey: n.componentKey.slice(0, 128) } : {}),
              ...(typeof n.setKey === 'string' && n.setKey ? { setKey: n.setKey.slice(0, 128) } : {}),
              ...(typeof n.mainName === 'string' && n.mainName ? { mainName: n.mainName.slice(0, 256) } : {}),
              ...(typeof n.setName === 'string' && n.setName ? { setName: n.setName.slice(0, 256) } : {}),
            }))
          : [],
        receivedAt: new Date().toISOString(),
      };
      // The selection is what tells the daemon WHICH file this socket belongs
      // to; the handshake carries no file identity. Two windows on the same
      // file would be indistinguishable for routing, so the newcomer takes
      // over and the older one is told it lost the bridge — the same
      // last-one-wins rule as before, now scoped per file instead of globally.
      const conn = conns.get(ws);
      if (conn) {
        const key = selection.fileKey ?? null;
        if (key && conn.fileKey !== key) {
          for (const [other, c] of conns) {
            if (other === ws || c.fileKey !== key) continue;
            if (other.readyState !== WebSocket.OPEN) continue;
            console.log(`[daemon] Superseding an older window on file ${key}`);
            for (const [id, pending] of pluginPendingRequests) {
              if (pending.ws !== other) continue;
              clearTimeout(pending.timeout);
              pending.reject(new Error('Plugin connection superseded by another Figma window'));
              pluginPendingRequests.delete(id);
            }
            try { other.send(JSON.stringify({ type: 'superseded' })); } catch {}
            try { other.close(4409, 'Superseded by another window'); } catch {}
          }
        }
        conn.fileKey = key;
        conn.fileName = selection.fileName ?? null;
        conn.editorType = selection.editorType ?? null;
        conn.selection = selection;
      }
    }
  });

  ws.on('close', () => {
    clearTimeout(authTimer);
    if (conns.delete(ws)) {
      console.log(`[daemon] Plugin disconnected — ${openConns().length} window(s) left`);
      // Only this socket's in-flight evals die with it; another window's
      // requests must not be collateral damage.
      for (const [id, pending] of pluginPendingRequests) {
        if (pending.ws !== ws) continue;
        clearTimeout(pending.timeout);
        pending.reject(new Error('Plugin disconnected'));
        pluginPendingRequests.delete(id);
      }
    }
  });

  ws.on('error', (error) => {
    console.error('[daemon] Plugin WebSocket error:', error.message);
  });
}

wss.on('connection', handlePluginSocket);
ipv6Wss.on('connection', handlePluginSocket);

// Cross-check the response signature against the OS: is the PID listening on
// `port` the one in our PID file? Returns true/false, or null when unknown
// (lsof/netstat unavailable, no PID file, unparsable output).
function pidFileOwnsPort(port) {
  try {
    const filePid = parseInt(readFileSync(PID_FILE, 'utf8').trim(), 10);
    if (!Number.isInteger(filePid)) return null;
    const raw = getPortPid(port);
    if (!raw) return null;
    // lsof -ti may list several PIDs (listener + connected clients).
    const pids = String(raw).split('\n').map((s) => parseInt(s.trim(), 10));
    if (!pids.some(Number.isInteger)) return null;
    return pids.includes(filePid);
  } catch {
    return null;
  }
}

// Probe whether the process holding `port` is one of our daemons — WITHOUT
// sending the session token (a foreign squatter on the port must never see
// it). Two signals: (1) our daemon answers unauthenticated /health with 403
// and a JSON `error` starting with "Unauthorized"; (2) the listening PID
// matches our PID file. Since the port fallback exists, a squatter MIMICKING
// the 403 shape would otherwise not be benign — it would make this daemon
// exit "already running" and silently deny the whole toolchain. The PID
// cross-check demotes a mimic to a plain foreign squatter (→ fallback);
// when the PID cannot be determined, the signature alone decides.
async function looksLikeOurDaemon(port) {
  try {
    // 800ms: a legitimate daemon with a briefly busy event loop must not be
    // misclassified as foreign — that would spawn a second daemon on the
    // next port (the exact split-brain this probe exists to prevent).
    const res = await fetch(`http://127.0.0.1:${port}/health`, {
      signal: AbortSignal.timeout(800),
    });
    if (res.status !== 403) return false;
    const body = await res.json();
    if (typeof body.error !== 'string' || !body.error.startsWith('Unauthorized')) return false;
    return pidFileOwnsPort(port) !== false;
  } catch {
    return false;
  }
}

function listenOn(server, port, host) {
  return new Promise((resolve, reject) => {
    const onError = (err) => reject(err);
    server.once('error', onError);
    server.listen(port, host, () => {
      server.removeListener('error', onError);
      resolve();
    });
  });
}

function closeListener(server) {
  return new Promise((resolve) => {
    if (!server.listening) return resolve();
    server.close(() => resolve());
  });
}

async function tryListen(port) {
  await listenOn(httpServer, port, '127.0.0.1');
  try {
    await listenOn(ipv6HttpServer, port, '::1');
  } catch (error) {
    await closeListener(httpServer);
    throw error;
  }
}

async function start() {
  // Split-brain guard: an existing daemon may sit on a LATER range port (its
  // start-time squatter since gone). Binding 3456 now would give two daemons,
  // with the plugin scan connecting to whichever answers first. Scan the whole
  // range for one of ours before binding anything. Skipped for an explicit
  // DAEMON_PORT — the singleton check below covers the single candidate.
  if (PORT_CANDIDATES.length > 1) {
    for (const port of PORT_CANDIDATES) {
      if (await looksLikeOurDaemon(port)) {
        console.log(`[daemon] Already running on port ${port} — exiting (singleton).`);
        process.exit(0);
      }
    }
  }

  for (const port of PORT_CANDIDATES) {
    try {
      await tryListen(port);
      boundPort = port;
      break;
    } catch (err) {
      if (err && err.code === 'EADDRINUSE') {
        if (await looksLikeOurDaemon(port)) {
          console.log(`[daemon] Port ${port} already owned by another daemon — exiting (singleton).`);
          process.exit(0);
        }
        console.log(`[daemon] Port ${port} held by a foreign process — trying next.`);
        continue;
      }
      console.error('[daemon] server error:', err);
      process.exit(1);
    }
  }

  if (boundPort === null) {
    console.error(
      `[daemon] All ports ${PORT_CANDIDATES.join(', ')} are busy. ` +
      `Free one of them or set DAEMON_PORT (note: the Figma plugin can only reach 3456-3460).`
    );
    process.exit(1);
  }

  try { writeFileSync(PID_FILE, String(process.pid)); } catch {}
  writePortFile(boundPort);
  console.log(`[daemon] figma-bridge-mcp daemon running on port ${boundPort} (pid ${process.pid})`);
  console.log(`[daemon] Mode: plugin (Safe Mode only)`);
  console.log(`[daemon] Idle timeout: ${IDLE_TIMEOUT_MS / 1000}s`);
  console.log(`[daemon] Auth: HTTP token + plugin access key required`);
}

// Unexpected errors after a successful bind (the pre-bind path handles its own).
for (const server of [httpServer, ipv6HttpServer]) {
  server.on('error', (err) => {
    if (boundPort === null) return; // tryListen owns pre-bind errors
    console.error('[daemon] server error:', err);
    process.exit(1);
  });
}

start();

// Graceful shutdown
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

// Drain window for in-flight /exec responses on shutdown. A long render can
// exceed this — the cap keeps `daemon restart` snappy; only shutdowns during
// an active eval wait at all.
const SHUTDOWN_DRAIN_MS = 10000;
let shuttingDown = false;

function shutdown() {
  if (shuttingDown) return;
  shuttingDown = true;
  console.log('[daemon] Shutting down...');
  if (idleTimer) clearTimeout(idleTimer);
  // Stop accepting new connections; established in-flight responses live on.
  httpServer.close(() => {});
  ipv6HttpServer.close(() => {});
  // Keep the plugin socket OPEN until in-flight evals have answered — closing
  // it first reset every running /exec with a connection error even though the
  // code kept executing in Figma (duplicate-mutation bait on manual restart).
  const deadline = Date.now() + SHUTDOWN_DRAIN_MS;
  const finish = () => {
    if (inFlightExecs > 0) {
      console.log(`[daemon] Forcing exit with ${inFlightExecs} eval(s) still in flight`);
    }
    for (const [ws] of conns) { try { ws.close(); } catch {} }
    // Only clear the port file if it still names our port — a dying old daemon
    // must not delete a newer daemon's published port.
    if (boundPort !== null) clearPortFile(process.env, boundPort);
    process.exit(0);
  };
  const tick = () => {
    if (inFlightExecs === 0 || Date.now() >= deadline) return finish();
    setTimeout(tick, 200);
  };
  tick();
}
