#!/usr/bin/env node

/**
 * Figma Safe MCP Daemon (Safe-Mode / plugin bridge only)
 *
 * The upstream figma-ds-cli daemon supported two transports: Yolo Mode (Chrome
 * DevTools Protocol, requires patching Figma) and Safe Mode (the Figma plugin
 * WebSocket). This build keeps ONLY the plugin bridge — there is no CDP path.
 *
 * Security features:
 * - Session token authentication on all HTTP routes (X-Daemon-Token header)
 * - Plugin access-key authentication on the WebSocket /plugin upgrade:
 *     · verifyClient: Host + Origin allowlist (blocks DNS rebinding / browsers)
 *     · first-message hello handshake carrying the access key (constant-time
 *       compared against the locally generated key) — closes the upstream gap
 *       where ANY local process could connect to /plugin and eval code in Figma
 * - No CORS headers (blocks cross-origin browser requests)
 * - Idle timeout auto-shutdown
 */

import { createServer } from 'http';
import { WebSocketServer, WebSocket } from 'ws';
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { createHash, timingSafeEqual } from 'crypto';
import { FigmaClient } from './figma-client.js';

const PORT = parseInt(process.env.DAEMON_PORT) || 3456;
// Safe-Mode build: the daemon is always the plugin bridge. Kept as a constant
// (not env-driven) so no configuration can re-enable a CDP path.
const MODE = 'plugin';
const IDLE_TIMEOUT_MS = parseInt(process.env.DAEMON_IDLE_TIMEOUT) || 60 * 60 * 1000; // 60 minutes

// ============ SECURITY ============

// Session token (HTTP routes) — generated by the CLI on daemon start.
// Env-overridable so tests can point at scratch files; defaults match cli-core.
const TOKEN_FILE = process.env.DAEMON_TOKEN_FILE || join(homedir(), '.figma-safe-mcp', '.daemon-token');
// Singleton PID file, claimed only by the daemon that wins the port bind.
const PID_FILE = process.env.DAEMON_PID_FILE || join(homedir(), '.figma-safe-mcp', 'daemon.pid');
let SESSION_TOKEN = null;

try {
  SESSION_TOKEN = readFileSync(TOKEN_FILE, 'utf8').trim();
  console.log('[daemon] Session token loaded');
} catch {
  console.error('[daemon] WARNING: No session token found. Daemon will reject all HTTP requests.');
}

// Plugin access key (WebSocket /plugin auth). Path passed by the MCP layer via
// PLUGIN_KEY_FILE. Absent/empty key ⇒ ALL plugin connections are rejected.
const PLUGIN_KEY_FILE = process.env.PLUGIN_KEY_FILE || '';
let PLUGIN_KEY = null;

if (PLUGIN_KEY_FILE) {
  try {
    const k = readFileSync(PLUGIN_KEY_FILE, 'utf8').trim();
    PLUGIN_KEY = k || null;
  } catch {
    PLUGIN_KEY = null;
  }
}
if (PLUGIN_KEY) {
  console.log('[daemon] Plugin access key loaded');
} else {
  console.error('[daemon] WARNING: No plugin access key. Plugin connections will be rejected. Run figma_connect.');
}

// Constant-time comparison of the access key (compare SHA-256 digests so the
// buffers are always equal length and the comparison never leaks length).
function keyMatches(provided) {
  if (!PLUGIN_KEY || typeof provided !== 'string' || provided.length === 0) return false;
  const a = createHash('sha256').update(PLUGIN_KEY).digest();
  const b = createHash('sha256').update(provided).digest();
  return timingSafeEqual(a, b);
}

/**
 * Validate HTTP request authentication and origin.
 * Returns null if valid, or an error string if rejected.
 */
function validateRequest(req) {
  // Layer 1: Host header validation (blocks DNS rebinding)
  const host = req.headers.host || '';
  if (!host.match(/^(localhost|127\.0\.0\.1)(:\d+)?$/)) {
    return 'Invalid host header';
  }

  // Layer 2: Session token (blocks unauthorized local processes)
  const token = req.headers['x-daemon-token'];
  if (!SESSION_TOKEN) {
    return 'No session token configured';
  }
  if (token !== SESSION_TOKEN) {
    return 'Invalid or missing token';
  }

  return null; // Valid
}

// ============ IDLE TIMEOUT ============

let lastActivityTime = Date.now();
let idleTimer = null;

function resetIdleTimer() {
  lastActivityTime = Date.now();
  if (idleTimer) clearTimeout(idleTimer);
  idleTimer = setTimeout(() => {
    const idleSecs = Math.round((Date.now() - lastActivityTime) / 1000);
    console.log(`[daemon] Idle for ${idleSecs}s — auto-shutting down`);
    shutdown();
  }, IDLE_TIMEOUT_MS);
}

resetIdleTimer();

// ============ PLUGIN MODE (SAFE) ============

// Only an authenticated plugin socket is stored here.
let pluginWs = null;
let pluginPendingRequests = new Map();
let pluginMsgId = 0;

function isPluginConnected() {
  return !!(pluginWs && pluginWs.readyState === WebSocket.OPEN);
}

async function evalViaPlugin(code) {
  if (!isPluginConnected()) {
    throw new Error('Plugin not connected. Launch the FigCli plugin in Figma and paste your access key.');
  }

  return new Promise((resolve, reject) => {
    const id = ++pluginMsgId;
    const timeout = setTimeout(() => {
      pluginPendingRequests.delete(id);
      reject(new Error('Plugin execution timeout (25s)'));
    }, 25000);

    pluginPendingRequests.set(id, { resolve, reject, timeout });

    try {
      pluginWs.send(JSON.stringify({ action: 'eval', id, code }));
    } catch (sendError) {
      clearTimeout(timeout);
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin send error: ${sendError.message}`));
    }
  });
}

// ============ UNIFIED EVAL ============

async function executeEval(code) {
  // Plugin handles its own top-level-return wrapping — send code as-is.
  return evalViaPlugin(code);
}

function getMode() {
  return isPluginConnected() ? 'safe' : 'disconnected';
}

// ============ HTTP SERVER ============

async function handleRequest(req, res) {
  resetIdleTimer();

  // SECURITY: No CORS headers. Block preflight outright.
  if (req.method === 'OPTIONS') {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'CORS preflight rejected' }));
    return;
  }

  // SECURITY: Validate authentication on all routes
  const authError = validateRequest(req);
  if (authError) {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized: ' + authError }));
    return;
  }

  // Health check
  if (req.url === '/health') {
    const pluginConnected = isPluginConnected();
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: pluginConnected ? 'ok' : 'disconnected',
      mode: getMode(),
      plugin: pluginConnected,
      pluginAuthenticated: pluginConnected, // only authenticated sockets are stored
      cdp: false,                            // no CDP path in the Safe-Mode build
      keyConfigured: !!PLUGIN_KEY,
      idleTimeoutMs: IDLE_TIMEOUT_MS
    }));
    return;
  }

  // Execute command
  if (req.url === '/exec' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      const MAX_RETRIES = 2;
      let lastError;

      let payload;
      try {
        payload = JSON.parse(body);
      } catch (e) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Invalid JSON body: ' + e.message }));
        return;
      }

      for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
        try {
          const { action, code, jsx, jsxArray, gap, vertical, collection } = payload;
          let result;

          const execWithTimeout = async (fn, timeoutMs = 30000) => {
            return Promise.race([
              fn(),
              new Promise((_, reject) =>
                setTimeout(() => reject(new Error(`Execution timeout (${timeoutMs / 1000}s)`)), timeoutMs)
              )
            ]);
          };

          switch (action) {
            case 'eval':
              result = await execWithTimeout(() => executeEval(code));
              break;
            case 'render': {
              // Parse JSX → plugin code, then execute via the plugin bridge.
              const parser = new FigmaClient();
              const renderCode = await parser.parseJSX(jsx);
              result = await execWithTimeout(() => executeEval(renderCode), 90000);
              break;
            }
            case 'render-batch': {
              const batchParser = new FigmaClient();
              if (collection) batchParser.setCollection(collection);
              const batchCode = await batchParser.parseJSXBatch(jsxArray, {
                gap: gap || 40,
                vertical: vertical || false
              });
              result = await execWithTimeout(() => executeEval(batchCode), 60000);
              break;
            }
            default:
              throw new Error(`Unknown action: ${action}`);
          }

          res.writeHead(200, { 'Content-Type': 'application/json' });
          res.end(JSON.stringify({ result, mode: getMode() }));
          return;
        } catch (error) {
          lastError = error;
          console.log(`[daemon] Attempt ${attempt + 1} failed: ${error.message}`);

          // NEVER retry a mutating render: executeEval may have already created
          // the frame before the response errored, and retrying would silently
          // produce a DUPLICATE. Reads/eval may still retry.
          if (payload.action === 'render' || payload.action === 'render-batch') break;

          // Safe Mode: wait briefly for a plugin reconnect before retrying.
          if (attempt < MAX_RETRIES) {
            for (let i = 0; i < 10; i++) {
              await new Promise(r => setTimeout(r, 200));
              if (isPluginConnected()) break;
            }
          }
        }
      }

      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: (lastError && lastError.message) || 'Execution failed' }));
    });
    return;
  }

  res.writeHead(404);
  res.end('Not found');
}

// ============ START SERVERS ============

const httpServer = createServer(handleRequest);

// WebSocket server for plugin connections.
// verifyClient is the first gate: only localhost Host headers and the sandboxed
// Figma plugin origin (null/absent) or figma.com are allowed through. Everything
// else — including any browser page on another origin — is rejected with 401.
const wss = new WebSocketServer({
  server: httpServer,
  path: '/plugin',
  verifyClient(info) {
    const req = info.req;
    const host = req.headers.host || '';
    if (!/^(localhost|127\.0\.0\.1)(:\d+)?$/.test(host)) return false;
    const origin = info.origin;
    if (origin && origin !== 'null' && !/^https:\/\/(www\.)?figma\.com$/.test(origin)) {
      return false;
    }
    return true;
  }
});

const AUTH_TIMEOUT_MS = 5000;

wss.on('connection', (ws) => {
  // Each socket starts unauthenticated. The FIRST message must be a valid
  // {type:'hello', key}. Until then the socket is not registered as pluginWs
  // and cannot drive any eval.
  let authenticated = false;

  // If no key is configured on the daemon, we can never authenticate — reject.
  if (!PLUGIN_KEY) {
    try { ws.send(JSON.stringify({ type: 'auth-error', reason: 'no-key-configured' })); } catch {}
    ws.close(4401, 'No access key configured on daemon');
    return;
  }

  const authTimer = setTimeout(() => {
    if (!authenticated) {
      try { ws.send(JSON.stringify({ type: 'auth-error', reason: 'timeout' })); } catch {}
      ws.close(4401, 'Authentication timeout');
    }
  }, AUTH_TIMEOUT_MS);

  ws.on('message', (data) => {
    resetIdleTimer();
    let msg;
    try {
      msg = JSON.parse(data.toString());
    } catch (e) {
      console.error('[daemon] Plugin message parse error:', e.message);
      return;
    }

    // --- Authentication gate ---
    if (!authenticated) {
      if (msg.type !== 'hello' || !keyMatches(msg.key)) {
        try { ws.send(JSON.stringify({ type: 'auth-error', reason: 'invalid-key' })); } catch {}
        ws.close(4401, 'Invalid access key');
        return;
      }
      // Authenticated.
      authenticated = true;
      clearTimeout(authTimer);
      pluginWs = ws;
      console.log(`[daemon] Plugin authenticated (version: ${msg.version || 'unknown'})`);
      try { ws.send(JSON.stringify({ type: 'hello-ack' })); } catch {}
      return;
    }

    // --- Authenticated message handling ---
    if (msg.type === 'result') {
      const pending = pluginPendingRequests.get(msg.id);
      if (pending) {
        clearTimeout(pending.timeout);
        pluginPendingRequests.delete(msg.id);
        if (msg.error) pending.reject(new Error(msg.error));
        else pending.resolve(msg.result);
      }
    }

    if (msg.type === 'batch-result') {
      const pending = pluginPendingRequests.get(msg.id);
      if (pending) {
        clearTimeout(pending.timeout);
        pluginPendingRequests.delete(msg.id);
        pending.resolve(msg.results);
      }
    }

    if (msg.type === 'ping') {
      try { ws.send(JSON.stringify({ type: 'pong' })); } catch {}
    }
  });

  ws.on('close', () => {
    clearTimeout(authTimer);
    // Only clear shared state if THIS socket was the authenticated one.
    if (ws === pluginWs) {
      console.log('[daemon] Plugin disconnected');
      pluginWs = null;
      for (const [, pending] of pluginPendingRequests) {
        clearTimeout(pending.timeout);
        pending.reject(new Error('Plugin disconnected'));
      }
      pluginPendingRequests.clear();
    }
  });

  ws.on('error', (error) => {
    console.error('[daemon] Plugin WebSocket error:', error.message);
  });
});

// Singleton guard: a second daemon (concurrent CLI race) fails to bind the port.
// Exit it cleanly before it does any work and without touching the PID file.
httpServer.on('error', (err) => {
  if (err && err.code === 'EADDRINUSE') {
    console.log(`[daemon] Port ${PORT} already owned by another daemon — exiting (singleton).`);
    process.exit(0);
  }
  console.error('[daemon] server error:', err);
  process.exit(1);
});

httpServer.listen(PORT, '127.0.0.1', () => {
  try { writeFileSync(PID_FILE, String(process.pid)); } catch {}
  console.log(`[daemon] figma-safe-mcp daemon running on port ${PORT} (pid ${process.pid})`);
  console.log(`[daemon] Mode: plugin (Safe Mode only)`);
  console.log(`[daemon] Idle timeout: ${IDLE_TIMEOUT_MS / 1000}s`);
  console.log(`[daemon] Auth: HTTP token + plugin access key required`);
});

// Graceful shutdown
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

function shutdown() {
  console.log('[daemon] Shutting down...');
  if (idleTimer) clearTimeout(idleTimer);
  if (pluginWs) pluginWs.close();
  httpServer.close(() => process.exit(0));
  setTimeout(() => process.exit(0), 3000);
}
