#!/usr/bin/env node

/**
 * Figma Safe MCP Daemon (Safe-Mode / plugin bridge only)
 *
 * The upstream figma-ds-cli daemon supported two transports: Yolo Mode (Chrome
 * DevTools Protocol, requires patching Figma) and Safe Mode (the Figma plugin
 * WebSocket). This build keeps ONLY the plugin bridge — there is no CDP path.
 *
 * Security features:
 * - Session token authentication on all HTTP routes (X-Daemon-Token header)
 * - Plugin access-key authentication on the WebSocket /plugin upgrade:
 *     · verifyClient: Host + Origin allowlist (blocks DNS rebinding / browsers)
 *     · first-message hello handshake carrying the access key (constant-time
 *       compared against the locally generated key) — closes the upstream gap
 *       where ANY local process could connect to /plugin and eval code in Figma
 * - No CORS headers (blocks cross-origin browser requests)
 * - Idle timeout auto-shutdown
 */

import { createServer } from 'http';
import { WebSocketServer, WebSocket } from 'ws';
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { createHash, timingSafeEqual } from 'crypto';
import { FigmaClient } from './figma-client.js';
import { parsePortRange, writePortFile, clearPortFile } from './lib/daemon-port.js';
import { getPortPid } from './platform.js';

// Explicit DAEMON_PORT means "exactly this port, no fallback" (the plugin can
// only reach the manifest range — off-range values are documented unsupported).
// Without it, the daemon walks the range and binds the first free port, which
// the plugin's parallel port scan finds on its own.
const EXPLICIT_PORT = parseInt(process.env.DAEMON_PORT, 10);
const PORT_CANDIDATES = Number.isInteger(EXPLICIT_PORT) && EXPLICIT_PORT > 0
  ? [EXPLICIT_PORT]
  : parsePortRange();
let boundPort = null; // set once the HTTP server wins a bind
// Safe-Mode build: the daemon is always the plugin bridge. Kept as a constant
// (not env-driven) so no configuration can re-enable a CDP path.
const MODE = 'plugin';
const IDLE_TIMEOUT_MS = parseInt(process.env.DAEMON_IDLE_TIMEOUT) || 60 * 60 * 1000; // 60 minutes

// ============ SECURITY ============

// Session token (HTTP routes) — generated by the CLI on daemon start.
// Env-overridable so tests can point at scratch files; defaults match cli-core.
const TOKEN_FILE = process.env.DAEMON_TOKEN_FILE || join(homedir(), '.figma-safe-mcp', '.daemon-token');
// Singleton PID file, claimed only by the daemon that wins the port bind.
const PID_FILE = process.env.DAEMON_PID_FILE || join(homedir(), '.figma-safe-mcp', 'daemon.pid');

// Session token is read PER REQUEST, not once at startup: startDaemon() rotates
// the token file before every spawn, and a lost spawn race (two CLIs starting
// daemons concurrently; the loser exits but has already rotated the file) would
// otherwise leave the surviving daemon holding a stale token — rejecting every
// request with 403 until a manual restart. The file is ~64 bytes and local;
// a read per request is negligible.
function readSessionToken() {
  try {
    return readFileSync(TOKEN_FILE, 'utf8').trim() || null;
  } catch {
    return null;
  }
}

if (readSessionToken()) {
  console.log('[daemon] Session token loaded');
} else {
  console.error('[daemon] WARNING: No session token found. Daemon will reject all HTTP requests.');
}

// Plugin access key (WebSocket /plugin auth). Path passed by the MCP layer via
// PLUGIN_KEY_FILE. Absent/empty key ⇒ ALL plugin connections are rejected.
const PLUGIN_KEY_FILE = process.env.PLUGIN_KEY_FILE || '';
let PLUGIN_KEY = null;

if (PLUGIN_KEY_FILE) {
  try {
    const k = readFileSync(PLUGIN_KEY_FILE, 'utf8').trim();
    PLUGIN_KEY = k || null;
  } catch {
    PLUGIN_KEY = null;
  }
}
if (PLUGIN_KEY) {
  console.log('[daemon] Plugin access key loaded');
} else {
  console.error('[daemon] WARNING: No plugin access key. Plugin connections will be rejected. Run figma_connect.');
}

// Constant-time comparison of the access key (compare SHA-256 digests so the
// buffers are always equal length and the comparison never leaks length).
function keyMatches(provided) {
  if (!PLUGIN_KEY || typeof provided !== 'string' || provided.length === 0) return false;
  const a = createHash('sha256').update(PLUGIN_KEY).digest();
  const b = createHash('sha256').update(provided).digest();
  return timingSafeEqual(a, b);
}

/**
 * Validate HTTP request authentication and origin.
 * Returns null if valid, or an error string if rejected.
 */
function validateRequest(req) {
  // Layer 1: Host header validation (blocks DNS rebinding)
  const host = req.headers.host || '';
  if (!host.match(/^(localhost|127\.0\.0\.1)(:\d+)?$/)) {
    return 'Invalid host header';
  }

  // Layer 2: Session token (blocks unauthorized local processes).
  // Read fresh per request so a token rotation under a live daemon heals
  // instead of wedging every consumer on 403.
  const token = req.headers['x-daemon-token'];
  const sessionToken = readSessionToken();
  if (!sessionToken) {
    return 'No session token configured';
  }
  if (token !== sessionToken) {
    return 'Invalid or missing token';
  }

  return null; // Valid
}

// ============ IDLE TIMEOUT ============

let lastActivityTime = Date.now();
let idleTimer = null;

function resetIdleTimer() {
  lastActivityTime = Date.now();
  if (idleTimer) clearTimeout(idleTimer);
  idleTimer = setTimeout(() => {
    const idleSecs = Math.round((Date.now() - lastActivityTime) / 1000);
    console.log(`[daemon] Idle for ${idleSecs}s — auto-shutting down`);
    shutdown();
  }, IDLE_TIMEOUT_MS);
}

resetIdleTimer();

// ============ PLUGIN MODE (SAFE) ============

// Only an authenticated plugin socket is stored here.
let pluginWs = null;
let pluginPendingRequests = new Map();
let pluginMsgId = 0;
// Last selection pushed by the plugin UI (null until the first push).
let lastSelection = null;

function isPluginConnected() {
  return !!(pluginWs && pluginWs.readyState === WebSocket.OPEN);
}

async function evalViaPlugin(code) {
  if (!isPluginConnected()) {
    throw new Error('Plugin not connected. Launch the FigCli plugin in Figma and paste your access key.');
  }

  return new Promise((resolve, reject) => {
    const id = ++pluginMsgId;
    const timeout = setTimeout(() => {
      pluginPendingRequests.delete(id);
      reject(new Error('Plugin execution timeout (25s)'));
    }, 25000);

    pluginPendingRequests.set(id, { resolve, reject, timeout });

    try {
      pluginWs.send(JSON.stringify({ action: 'eval', id, code }));
    } catch (sendError) {
      clearTimeout(timeout);
      pluginPendingRequests.delete(id);
      reject(new Error(`Plugin send error: ${sendError.message}`));
    }
  });
}

// ============ UNIFIED EVAL ============

async function executeEval(code) {
  // Plugin handles its own top-level-return wrapping — send code as-is.
  return evalViaPlugin(code);
}

function getMode() {
  return isPluginConnected() ? 'safe' : 'disconnected';
}

// ============ HTTP SERVER ============

async function handleRequest(req, res) {
  resetIdleTimer();

  // SECURITY: No CORS headers. Block preflight outright.
  if (req.method === 'OPTIONS') {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'CORS preflight rejected' }));
    return;
  }

  // SECURITY: Validate authentication on all routes
  const authError = validateRequest(req);
  if (authError) {
    res.writeHead(403, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Unauthorized: ' + authError }));
    return;
  }

  // Health check
  if (req.url === '/health') {
    const pluginConnected = isPluginConnected();
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      status: pluginConnected ? 'ok' : 'disconnected',
      mode: getMode(),
      plugin: pluginConnected,
      pluginAuthenticated: pluginConnected, // only authenticated sockets are stored
      cdp: false,                            // no CDP path in the Safe-Mode build
      keyConfigured: !!PLUGIN_KEY,
      idleTimeoutMs: IDLE_TIMEOUT_MS
    }));
    return;
  }

  // Execute command
  if (req.url === '/exec' && req.method === 'POST') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', async () => {
      let payload;
      try {
        payload = JSON.parse(body);
      } catch (e) {
        res.writeHead(400, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: 'Invalid JSON body: ' + e.message }));
        return;
      }

      // NO retries for ANY action: every action ultimately evals arbitrary,
      // usually MUTATING code in the plugin. On a timeout/disconnect the code
      // may still complete in Figma — re-sending it silently DUPLICATES the
      // mutation (frames, variables, node edits). The earlier retry loop
      // exempted only render/render-batch and re-ran evals; that was wrong.
      try {
        const { action, code, jsx, jsxArray, gap, vertical, collection } = payload;
        let result;

        const execWithTimeout = async (fn, timeoutMs = 30000) => {
          return Promise.race([
            fn(),
            new Promise((_, reject) =>
              setTimeout(() => reject(new Error(`Execution timeout (${timeoutMs / 1000}s)`)), timeoutMs)
            )
          ]);
        };

        switch (action) {
          case 'eval':
            result = await execWithTimeout(() => executeEval(code));
            break;
          case 'render': {
            // Parse JSX → plugin code, then execute via the plugin bridge.
            const parser = new FigmaClient();
            const renderCode = await parser.parseJSX(jsx);
            result = await execWithTimeout(() => executeEval(renderCode), 90000);
            break;
          }
          case 'render-batch': {
            const batchParser = new FigmaClient();
            if (collection) batchParser.setCollection(collection);
            const batchCode = await batchParser.parseJSXBatch(jsxArray, {
              gap: gap || 40,
              vertical: vertical || false
            });
            result = await execWithTimeout(() => executeEval(batchCode), 60000);
            break;
          }
          default:
            throw new Error(`Unknown action: ${action}`);
        }

        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ result, mode: getMode() }));
      } catch (error) {
        console.log(`[daemon] /exec failed: ${error.message}`);
        res.writeHead(500, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: error.message || 'Execution failed' }));
      }
    });
    return;
  }

  // Last selection the plugin UI pushed (button or selectionchange event).
  // Read by the MCP tool figma_selection.
  if (req.url === '/selection') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      selection: lastSelection,
      pluginConnected: isPluginConnected(),
    }));
    return;
  }

  // Force the plugin to reconnect: close its socket — the plugin UI re-scans
  // the whole port range automatically. Used by `daemon reconnect` (this route
  // did not exist before; the command always failed on the 404 fallthrough).
  if (req.url === '/reconnect') {
    const hadPlugin = isPluginConnected();
    if (hadPlugin) {
      try { pluginWs.close(); } catch {}
    }
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, hadPlugin }));
    return;
  }

  res.writeHead(404);
  res.end('Not found');
}

// ============ START SERVERS ============

const httpServer = createServer(handleRequest);

// WebSocket server for plugin connections.
// verifyClient is the first gate: only localhost Host headers and the sandboxed
// Figma plugin origin (null/absent) or figma.com are allowed through. Everything
// else — including any browser page on another origin — is rejected with 401.
const wss = new WebSocketServer({
  server: httpServer,
  path: '/plugin',
  verifyClient(info) {
    const req = info.req;
    const host = req.headers.host || '';
    if (!/^(localhost|127\.0\.0\.1)(:\d+)?$/.test(host)) return false;
    const origin = info.origin;
    if (origin && origin !== 'null' && !/^https:\/\/(www\.)?figma\.com$/.test(origin)) {
      return false;
    }
    return true;
  }
});

// ws re-emits the underlying server's errors (including the EADDRINUSE of a
// failed bind attempt) on the WebSocketServer. Without a listener that becomes
// an uncaught 'error' event and kills the process before the fallback loop in
// start() can try the next port. The HTTP-server side owns error handling.
wss.on('error', () => {});

const AUTH_TIMEOUT_MS = 5000;

wss.on('connection', (ws) => {
  // Each socket starts unauthenticated. The FIRST message must be a valid
  // {type:'hello', key}. Until then the socket is not registered as pluginWs
  // and cannot drive any eval.
  let authenticated = false;

  // If no key is configured on the daemon, we can never authenticate — reject.
  if (!PLUGIN_KEY) {
    try { ws.send(JSON.stringify({ type: 'auth-error', reason: 'no-key-configured' })); } catch {}
    ws.close(4401, 'No access key configured on daemon');
    return;
  }

  const authTimer = setTimeout(() => {
    if (!authenticated) {
      try { ws.send(JSON.stringify({ type: 'auth-error', reason: 'timeout' })); } catch {}
      ws.close(4401, 'Authentication timeout');
    }
  }, AUTH_TIMEOUT_MS);

  ws.on('message', (data) => {
    resetIdleTimer();
    let msg;
    try {
      msg = JSON.parse(data.toString());
    } catch (e) {
      console.error('[daemon] Plugin message parse error:', e.message);
      return;
    }

    // --- Authentication gate ---
    if (!authenticated) {
      if (msg.type !== 'hello' || !keyMatches(msg.key)) {
        try { ws.send(JSON.stringify({ type: 'auth-error', reason: 'invalid-key' })); } catch {}
        ws.close(4401, 'Invalid access key');
        return;
      }
      // Authenticated.
      authenticated = true;
      clearTimeout(authTimer);
      pluginWs = ws;
      console.log(`[daemon] Plugin authenticated (version: ${msg.version || 'unknown'})`);
      try { ws.send(JSON.stringify({ type: 'hello-ack' })); } catch {}
      return;
    }

    // --- Authenticated message handling ---
    if (msg.type === 'result') {
      const pending = pluginPendingRequests.get(msg.id);
      if (pending) {
        clearTimeout(pending.timeout);
        pluginPendingRequests.delete(msg.id);
        if (msg.error) pending.reject(new Error(msg.error));
        else pending.resolve(msg.result);
      }
    }

    if (msg.type === 'batch-result') {
      const pending = pluginPendingRequests.get(msg.id);
      if (pending) {
        clearTimeout(pending.timeout);
        pluginPendingRequests.delete(msg.id);
        pending.resolve(msg.results);
      }
    }

    if (msg.type === 'ping') {
      try { ws.send(JSON.stringify({ type: 'pong' })); } catch {}
    }

    // Selection push from the plugin (automatic, debounced selectionchange
    // events). Cached here; served via GET /selection so the MCP tool
    // figma_selection can read it. Only the authenticated socket reaches
    // this handler.
    if (msg.type === 'selection' && msg.selection && typeof msg.selection === 'object') {
      lastSelection = {
        page: String(msg.selection.page || ''),
        total: Number(msg.selection.total) || 0,
        nodes: Array.isArray(msg.selection.nodes)
          ? msg.selection.nodes.slice(0, 50).map((n) => ({
              id: String(n.id || ''),
              name: String(n.name || ''),
              type: String(n.type || ''),
              ...(Number.isFinite(n.width) ? { width: n.width } : {}),
              ...(Number.isFinite(n.height) ? { height: n.height } : {}),
            }))
          : [],
        receivedAt: new Date().toISOString(),
      };
    }
  });

  ws.on('close', () => {
    clearTimeout(authTimer);
    // Only clear shared state if THIS socket was the authenticated one.
    if (ws === pluginWs) {
      console.log('[daemon] Plugin disconnected');
      pluginWs = null;
      for (const [, pending] of pluginPendingRequests) {
        clearTimeout(pending.timeout);
        pending.reject(new Error('Plugin disconnected'));
      }
      pluginPendingRequests.clear();
    }
  });

  ws.on('error', (error) => {
    console.error('[daemon] Plugin WebSocket error:', error.message);
  });
});

// Cross-check the response signature against the OS: is the PID listening on
// `port` the one in our PID file? Returns true/false, or null when unknown
// (lsof/netstat unavailable, no PID file, unparsable output).
function pidFileOwnsPort(port) {
  try {
    const filePid = parseInt(readFileSync(PID_FILE, 'utf8').trim(), 10);
    if (!Number.isInteger(filePid)) return null;
    const raw = getPortPid(port);
    if (!raw) return null;
    // lsof -ti may list several PIDs (listener + connected clients).
    const pids = String(raw).split('\n').map((s) => parseInt(s.trim(), 10));
    if (!pids.some(Number.isInteger)) return null;
    return pids.includes(filePid);
  } catch {
    return null;
  }
}

// Probe whether the process holding `port` is one of our daemons — WITHOUT
// sending the session token (a foreign squatter on the port must never see
// it). Two signals: (1) our daemon answers unauthenticated /health with 403
// and a JSON `error` starting with "Unauthorized"; (2) the listening PID
// matches our PID file. Since the port fallback exists, a squatter MIMICKING
// the 403 shape would otherwise not be benign — it would make this daemon
// exit "already running" and silently deny the whole toolchain. The PID
// cross-check demotes a mimic to a plain foreign squatter (→ fallback);
// when the PID cannot be determined, the signature alone decides.
async function looksLikeOurDaemon(port) {
  try {
    // 800ms: a legitimate daemon with a briefly busy event loop must not be
    // misclassified as foreign — that would spawn a second daemon on the
    // next port (the exact split-brain this probe exists to prevent).
    const res = await fetch(`http://127.0.0.1:${port}/health`, {
      signal: AbortSignal.timeout(800),
    });
    if (res.status !== 403) return false;
    const body = await res.json();
    if (typeof body.error !== 'string' || !body.error.startsWith('Unauthorized')) return false;
    return pidFileOwnsPort(port) !== false;
  } catch {
    return false;
  }
}

function tryListen(port) {
  return new Promise((resolve, reject) => {
    const onError = (err) => reject(err);
    httpServer.once('error', onError);
    httpServer.listen(port, '127.0.0.1', () => {
      httpServer.removeListener('error', onError);
      resolve();
    });
  });
}

async function start() {
  // Split-brain guard: an existing daemon may sit on a LATER range port (its
  // start-time squatter since gone). Binding 3456 now would give two daemons,
  // with the plugin scan connecting to whichever answers first. Scan the whole
  // range for one of ours before binding anything. Skipped for an explicit
  // DAEMON_PORT — the singleton check below covers the single candidate.
  if (PORT_CANDIDATES.length > 1) {
    for (const port of PORT_CANDIDATES) {
      if (await looksLikeOurDaemon(port)) {
        console.log(`[daemon] Already running on port ${port} — exiting (singleton).`);
        process.exit(0);
      }
    }
  }

  for (const port of PORT_CANDIDATES) {
    try {
      await tryListen(port);
      boundPort = port;
      break;
    } catch (err) {
      if (err && err.code === 'EADDRINUSE') {
        if (await looksLikeOurDaemon(port)) {
          console.log(`[daemon] Port ${port} already owned by another daemon — exiting (singleton).`);
          process.exit(0);
        }
        console.log(`[daemon] Port ${port} held by a foreign process — trying next.`);
        continue;
      }
      console.error('[daemon] server error:', err);
      process.exit(1);
    }
  }

  if (boundPort === null) {
    console.error(
      `[daemon] All ports ${PORT_CANDIDATES.join(', ')} are busy. ` +
      `Free one of them or set DAEMON_PORT (note: the Figma plugin can only reach 3456-3460).`
    );
    process.exit(1);
  }

  try { writeFileSync(PID_FILE, String(process.pid)); } catch {}
  writePortFile(boundPort);
  console.log(`[daemon] figma-safe-mcp daemon running on port ${boundPort} (pid ${process.pid})`);
  console.log(`[daemon] Mode: plugin (Safe Mode only)`);
  console.log(`[daemon] Idle timeout: ${IDLE_TIMEOUT_MS / 1000}s`);
  console.log(`[daemon] Auth: HTTP token + plugin access key required`);
}

// Unexpected errors after a successful bind (the pre-bind path handles its own).
httpServer.on('error', (err) => {
  if (boundPort === null) return; // tryListen owns pre-bind errors
  console.error('[daemon] server error:', err);
  process.exit(1);
});

start();

// Graceful shutdown
process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

function shutdown() {
  console.log('[daemon] Shutting down...');
  if (idleTimer) clearTimeout(idleTimer);
  if (pluginWs) pluginWs.close();
  // Only clear the port file if it still names our port — a dying old daemon
  // must not delete a newer daemon's published port.
  if (boundPort !== null) clearPortFile(process.env, boundPort);
  httpServer.close(() => process.exit(0));
  setTimeout(() => process.exit(0), 3000);
}
